services:
  backend:
    restart: unless-stopped
    build: ./backend

  gateway:
    restart: unless-stopped
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1/" ]
      interval: 5s
      timeout: 3s
      retries: 5
