[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "transactionManager.settings_test"

# solves problem with same file names in diff dirs
addopts = "--import-mode=importlib"

markers = [
    "unit: marks unit tests",
    "integration: marks integration tests",
    "e2e: marks end-to-end tests",
    "slow: marks slow tests",
]
