# Generated by Django 5.2.3 on 2025-08-06 11:06

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import naivedatetimefield
from django.db import migrations, models

import transactionManagerProcessor.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("timestamp", naivedatetimefield.NaiveDateTimeField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=transactionManagerProcessor.models._get_currencies,
                        max_length=3,
                    ),
                ),
                ("customer_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("product_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("quantity", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TransactionCSV",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("file", models.FileField(upload_to="csv_transactions_files/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CSVProcessingStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=transactionManagerProcessor.models._get_csv_processing_statuses,
                        default="processing",
                        max_length=15,
                    ),
                ),
                ("no_fails", models.PositiveIntegerField(default=0)),
                ("no_successes", models.PositiveIntegerField(default=0)),
                (
                    "transaction_csv",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transactionManagerProcessor.transactioncsv",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
