# Generated by Django 5.2.3 on 2025-07-02 20:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
