# Generated by Django 5.2.3 on 2025-07-02 20:46

import transactionManagerProcessor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactionManagerProcessor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=transactionManagerProcessor.models.NaiveDateTimeField(),
        ),
    ]
