# Generated by Django 5.2.3 on 2025-08-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactionManagerProcessor", "0002_alter_transaction_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="customer_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="product_id",
            field=models.UUIDField(db_index=True),
        ),
    ]
