# Generated by Django 5.2.3 on 2025-07-04 18:20

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionManagerProcessor', '0003_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
