# Generated by Django 5.2.3 on 2025-08-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactionManagerProcessor", "0003_alter_transaction_customer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
