# Generated by Django 5.2.3 on 2025-08-25 17:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactionManagerProcessor", "0004_alter_transaction_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="id",
            new_name="transaction_id",
        ),
    ]
