# Generated by Django 5.2.3 on 2025-07-15 16:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionManagerProcessor', '0005_alter_transaction_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCSV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='csv_transactions_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CSVProcessingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_fails', models.IntegerField(default=0)),
                ('no_sucesses', models.IntegerField(default=0)),
                ('csv_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactionManagerProcessor.transactioncsv')),
            ],
        ),
    ]
