name: Test Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.test.txt -r backend/requirements.txt
    - name: Set pythonpath
      run: |
        echo "PYTHONPATH=$PYTHONPATH:$(pwd)/backend/transactionManager" >> $GITHUB_ENV
    - name: Create log dir
      run: |
        mkdir -p backend/transactionManager/logs
    - name: Run tests
      run: |
        pytest backend
