name: Test Backend

on:
  push:
    branches: [ "chore/uv" ]
  pull_request:
    branches: [ "chore/uv" ]

jobs:
  test-backend:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
          version: "0.8.22"

    - name: Sync dependencies
      run: |
        uv sync --locked

    - name: Set pythonpath
      run: |
        echo "PYTHONPATH=$PYTHONPATH:$(pwd)/transactionManager" >> $GITHUB_ENV

    - name: Set .venv path
      run: |
        echo "PATH=$(pwd)/.venv/bin:$PATH" >> $GITHUB_ENV

    - name: Create log dir
      run: |
        mkdir -p transactionManager/logs

    - name: Run tests
      run: |
        pytest
