name: Test Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
          version: "0.8.22"

    - name: Sync dependencies
      run: |
        uv sync --directory backend --locked

    - name: Set pythonpath
      run: |
        echo "PYTHONPATH=$PYTHONPATH:$(pwd)/backend/transactionManager" >> $GITHUB_ENV

    - name: Set .venv path
      run: |
        echo "PATH=$(pwd)/backend/.venv/bin:$PATH" >> $GITHUB_ENV

    - name: Create log dir
      run: |
        mkdir -p backend/transactionManager/logs

    - name: Run tests
      run: |
        pytest backend
